<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Version>0.1.0</Version>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>

        <InvariantGlobalization>false</InvariantGlobalization>

        <CETCompat>false</CETCompat>
    </PropertyGroup>
</Project>
